#!/bin/bash

mkdir genome
cd genome
ln -s ../../genomes/IRBB7/IRBB7ctg.fa ./
cd ..

mkdir reads
cd reads
ln -s ../../reads/RAMPAGE/GSF-1119_S1_R1_001.fastq ./GSF-1119_S1.R1.fq
ln -s ../../reads/RAMPAGE/GSF-1119_S1_R2_001.fastq ./GSF-1119_S1.R2.fq
cd ..

mkdir results
