#!/bin/bash
#

LABEL="IRBB7"
RUNLABEL="${LABEL}-MvsC"
SAMPLES="IRBB7M1 IRBB7M2  IRBB7C1 IRBB7C2"
GENELIST=""
ISOFORMS=""
for sample in ${SAMPLES}
do
  GENELIST="${GENELIST} ${sample}/${sample}-bowtie2.genes.results "
  ISOFORMS="${ISOFORMS} ${sample}/${sample}-bowtie2.isoforms.results "
done


rsem-generate-data-matrix ${GENELIST} > ${RUNLABEL}.genes.tab
rsem-generate-data-matrix ${ISOFORMS} > ${RUNLABEL}.isoforms.tab

rsem-run-ebseq                           ${RUNLABEL}.genes.tab     2,2  ${RUNLABEL}.genes.DE
rsem-run-ebseq --ngvector ${LABEL}.ngvec ${RUNLABEL}.isoforms.tab  2,2  ${RUNLABEL}.isoforms.DE

rsem-control-fdr ${RUNLABEL}.genes.DE     0.01  ${RUNLABEL}.genes.DE.01
rsem-control-fdr ${RUNLABEL}.isoforms.DE  0.01  ${RUNLABEL}.isoforms.DE.01

mkdir deMvsC
mv *IRBB7-MvsC* deMvsC/

Rscript dgeMvsC.Rscript 0.9 2.0 1000000 decreasing up
Rscript dgeMvsC.Rscript 0.9   0     0.5 increasing down
mv *IRBB7-MvsC* deMvsC/
